name = "leanslop"
version = "0.1.0"
defaultTargets = ["LeanSlop"]
precompileModules = true
moreLinkArgs = ["/usr/lib/x86_64-linux-gnu/libcurl.so"]

[[require]]
name = "leanCurl"
source = { type="git", url="https://github.com/bergmannjg/leanCurl", rev="main" }

[[lean_lib]]
name = "LeanSlop"
